### ISSUE TITLE
DMA setup appears to use zero for burst transfer

### ISSUE THREAD

**Issue by daveythacher** [hzeller/rpi-gpio-dma-demo#3]
DMA configuration would appear to suggest low performance. Interesting use of d_stride when you could use 128 with no d_inc. Conceptually it does not appear this configuration understands the advantages and pitfalls of DMA, however wastes no time slandering it.  

DMA is a forum of parallelization at system bus. Behavior at memory and/or system bus can cause problems. Bursts would generally improve performance, however writing to GPIO directly would be interesting considering the DMA speed. I see no reason why cached memory is a factor here as that applies to the processor which is never supposed to do IO ever.

Conceptually I am confused why this is done this way. This is a user space application for embedded Linux, which would suggest unstable memory bandwidth. DMA would help by avoiding cache instability however system bus and memory instability is still a valid concern. Timing here becomes a concern, however if able to work mostly in cache using large amounts of memory could allow parallel execution as DMA becomes another process. 

However given the amount of overhead in terms of the CPU I would expect the realistic performance of such GPIO operations to be low. These two could fight for contention of the same resource. Moving to SPI via external hardware like PIC32MX110F032B would allow SPI->DMA->PMP for LED project. SPIDev would use DMA Undercovers for transfers larger than 96 bytes.   

Setting up DMA has overhead associated with it, so generally you do not do it for single bytes. Unless you want parallelization to allow context swapping away. Processing GPIO values will likely be fairly computationally intensive in terms of cycles, using large memory tables could prevent repeated work. This would enable free cycles and less cache congestion, however system bus/memory contention may increase.   

Limited exist on some systems in terms of memory and processing capabilities which may render many of the displayed GPIO rates unobtainable. Efficiency here sounds like a really strange notion for software based IO. GPIO wries can cause delays or unstable software architectures. In user space the premise of this gets much worse.   

Overall this seems like a poor understanding of software and hardware. Also a premise of locality violations in a number of terms. I think it should be noted most of these benchmarks show ideal performance with a single core blasting the GPIO registers, which will likely stall the core.   

Overall the Pi is capable in some areas more than others. It's peripherals bear this out. The notion of set and clear for example. Certain features of DMA another example. The Pi is constrained in terms of interfacing, it's best interface as far as I can tell is SPI. It has DMA and could support context switching safely to allow clean software and not impose on other processes. The memory performance would likely be minimal due the SPIs bandwidth and limited overhead.   

Pure software in this context is a violation of software and user space good practices!

**Comment by daveythacher** [comment]
It should be observed that this document mentions AXI bus: https://www.raspberrypi.org/app/uploads/2012/02/BCM2835-ARM-Peripherals.pdf

Also certain types of memory are known for their latency and tend to respond well to burst transactions. Closer inspection of AXI would also explain some of this potentially. It would depend how the bus is organized on this version, which could vary between versions also.

I do not know what the AXI and OS will do when moving from high speed bus to low speed bus. I also do not know how to regulate speed of writes to GPIO. Come DMAs support this, however conceptually I am not sure there is much point for that in a core that clearly targets an OS.

Cached memory is nice for speeding up cycle based processing which uses lots of cycles and complicates software along with other processes. However it does lower memory usage, but can cause/have cache issues.

**Comment by hzeller** [comment]
Note, this is meant as a experiment of how to set the GPIO pins in various ways they have been observed in the wild drilled down to their core and to compare. They do not suggest any way what is best. So the critique that this is a "poor understanding of software and hardware" does not really apply here.

If you know different ways to use DMA or other hardware features of the Raspberry Pi to send a sequence of bits to the GPIO pins, please add more examples and contribute with a pull request.

**Comment by daveythacher** [comment]
Page 51 of BCM2835 ARM Peripherals, which describes x_TI registers at offset (0x100 * x + 0x8) for DMA Channel x. Or the DMA transfer information register, which mentions a field called BURST_LENGTH (bits 15:12). In the description of Burst transfer length it describes bursts.

Page 64 in section 4.3 it continues its mentioning of burst and declares they are AXI burst consistent with AXI protocol which is a bus interface. Commonly used by Xilinx in FPGAs. Now it does mention some kind of implementational issue.

I honestly dislike this approach, it violates a ton. Then to top it off it asserts there is an issue with DMA. Tthe notion of DMA is fine, but the Pi has a terrible underlying notion. Rather than understand that you present it incorrectly thus forth.

Converting the SPI to PMP can be done in simple logic gates too! Granted there is performance issue possible there but for a single or dual channel HUB75 interface it would likely tie your software approach. It is cheaper to do it in software, perhaps. However you are really making a library with terrible system performance as a dependency.

That has been the point all along. You claim overengineered, but really its commonly referred to in this case as actually engineered! This all software bit bang is terrible in software and hardware terms. Rather than work around this you slander it or present the possibility as being infeasible. The Pi is poorly suited for this task in a number of instances. So lets keep this in focus.

Again I have mentioned the issue too. Its not DMA, its either the DMAs configuration or the underlying interface of the GPIO. Again if familiar with the Xilinx IP for both this would probably jump out at you. DMA is conceptually based on IO or larger transfers. To do small individual ones is a waste of time.

To bring up aspects of cached memory which usually DMA does not access under normal workflows makes little sense. Again depends of AXI or system bus design. Cache memory could be faster from one perspective, however its is incorrect to assume it is a limitation of DMA. Also did you consider using SG, which the Pi probably does not support either. Seeing as it basically supports nothing useful correctly.

Further more the core is not likely able on all versions of Pi to accelerate certain operating correctly. Which however could cause cache thrashing. Again this should not be done on the Pi!!! Even a the BeagleBone Black could do better.

**Comment by hzeller** [comment]
Not sure what your point is. Everyone knows that it is a silly  to expect that the Pi is good outputting realtime-qualifying data to the GPIO, so there is no point in getting upset about anything. Which you seem you are.
Wherever it is used, it is mostly because you can do it without any additional hardware, as you said "cheaper to do in software". It would not be used for anything serious anyway.
If you have a piece of hardware that allows bitbanging,people will do it, no matter if there are better ways. Here, some of these are explored.

If you read the Repo, you see that this is mostly a simple example how to use GPIO in the Raspberry Pi in various ways. There are a ton of ways to get this with better suited hardware, but the _focus_ on this is to use the Pi, not how to avoid the Pi as it would not be good at it anyway.

The code was written a long time ago to gather some ways how to access the GPIOs. If you find inaccuracies in the description or like to contribute an example how to configure the hardware to do the same thing in a better way using the ARM Peripheral documentation, pull requests are accepted.

**Comment by daveythacher** [comment]
This in my opinion is deceptive and off topic. The Pi was designed to conceptually teach programming. In my opinion your usage of the Pi undermines this. Bit banging has plagued Arduino and there are a number of more proper techniques available there. Yet due mostly for this type of thinking those are never mentioned.

The Pi is at best embedded Linux however more realistically its a general purpose computer. Among embedded systems the Pi is really poor. Honestly these tests show two things. Your testing methodology is terrible and incomplete. More importantly they show that the Pi should never have been used as these tests suggest the Pi is poorly suited. So using it anyway to me see suggests this narrative is poor.

I was always concerned for how the Pi would be used. The notion of real time qualifying data is such a BS term. Embedded Linux is a poor candidate for the entire notion of real time, let alone user space bit banging in a round robin/priority scheduler with overhead. Python is just dumb, but now people are pushing Java into a light switch.

Now embedded system can be used for certain components if properly factored in. Some tasks are not overly real time in nature or are not overly critical. You can usually compartmentalize real time logic, which I think is my point! 

The task of say a LED matrix which needs to be multiplexed for proper presentation would hardly suit this. Then factor in other tasks like say TLS or web server, well then things get interesting. Never mind if you need additional pins for other aspects of the project. 

Heck even generating certain computations for software PWM can become expensive for the Pi depending on size. It just so happens the IO and overhead holds this down. Conceptually this is massive problem for education. As foundationally this is software doing IO and attempting to use a ton of clock speed to pull it off. Power consumption under current/known technology makes this a bad idea.

However to create a library which bit bangs, makes absolutely no sense to me at all. This notion conceptually breaks nearly every known concept in application development and embedded systems. These tests test a small set and give the illusion to something that is false.

There are better ways even for a general purpose computer let alone a Pi. This cost argument is completely insane here. I argue even the nature of the exploration is insane. This type of logic is common among certain fields, most of whom will not survive long term. 

Conceptually there was once an effort which would enable some of these views. However that has mostly been corrupted by AI, the Cloud, Quantum, Python, Pi, Java, etc. Most of which was an imperfect understand of their significance. It breed this type of arrogance, "modernism", and economics.

Even under the most dense economic rigging. People in my opinion are just behind the curve and yet somehow think they are ahead of it. In my honest opinion people do not understand software properly. This is not computation, this is work. The Pi is a processor...not a controller.

Hardware can do everything. Economics of processors are hardware economics, not software. Hardware can enable software to do just about anything. Economics of software is a lie for the weak minded.

**Comment by hzeller** [comment]
I fully agree that a lot of things people do is outside what _should_ be done.

You shouldn't use a Pi to drive an LED matrix for more than a demo because it is not realtime from hardware (dynamic ram, bus contention, ...) to operating system.
You shouldn't use the Pi to demonstrate how to create a FM radio transmission
You shouldn't also use a PC to drive CNC machines with the printer port.
You shouldn't use the USER port on a C64 to drive toy robots.
You shouldn't write a web-server in Java.
You shouldn't use Python for ... really anything.
... the list goes on.

However, countless people have started their engineering careers being curious what could be done and learn on the way what are good and not so good idea; you shouldn't disregard this. I am also worried about Python or Java programmers staying where they are or using the Raspberry Pi for more than being toy or seriously considering it to be a controller of something useful - but if there are a few under them for which the initial curiosity will carry them further, that is great. The Raspberry Pi is a teaching platform mostly, so this is one stepstone for them to grasp limitations and e.g. will understand that realtime is a bad idea on a general-purpose computer. Learning comes from failure, not from things that work.

The best rocket scientist will have started with a go-cart or were playing with a garden hose to see how it creates thrust when they were a kid. Even though this is hardly anything adequate, it might have sparked what they have become.

If people want to use the GPIO to explore controlling the external world, I fully support them in their quest.

You are free to not use the Raspberry Pi for that kind of exploration.
